name: Automated API tests using Newman

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Newman
        run: npm install -g newman

      - name: Run API tests
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }} # Postman API key stored as a GitHub secret
        run: |
          newman run "https://api.getpostman.com/collections/23897168-6bea315a-b162-4078-afc6-d607f477e4c8?apikey=$POSTMAN_API_KEY" \
          --environment "https://api.getpostman.com/environments/23897168-fecbbd6b-5f2c-48e2-b136-5b3802b06dea?apikey=$POSTMAN_API_KEY"
