name: Automated API tests using Postman CLI

on: [push]

jobs:
  api-requests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install newman
      run: npm install -g newman

    - name: Run collection using Newman
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }} # Using your stored client_id
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }} # Using your stored client_secret
      run: |
        newman run path/to/your/collection.json -e path/to/your/environment.json --global-var "client_id=$CLIENT_ID" --global-var "client_secret=$CLIENT_SECRET"
